services:
  projeto:
    image: brunozalc/apicloud:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/dogfacts      
      - SECRET_KEY=zJsD2ve8DGT5iWiYZmQjGqXlZPXP+p2DNwTjhpGtN4E=
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dogfacts
    ports:
      - 5432:5432
    networks:
        - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dogfacts"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
