site_name: Projeto Cloud 2024.2
site_url: https://brunozalc.github.io/projeto-cloud/
repo_url: https://github.com/brunozalc/projeto-cloud
edit_uri: edit/main/docs/
nav:
  - home: index.md 
  - docker:
    - download e uso: docker/uso.md
    - API: docker/api.md 
  - aws:
    - visão geral: aws/aws.md
theme: 
  name: terminal
  palette: dark
  features:
    - footer.prev_next
    - navigation.side.indexes
    - navigation.side.toc.hide
    - revision.date 
    - revision.history
  custom_dir: overrides
plugins:
  - search
  - git-revision-date
