apiVersion: v1
kind: Service
metadata:
  name: projeto
spec:
  type: LoadBalancer  # or NodePort, depending on your setup
  selector:
    app: projeto
  ports:
    - port: 8000
      targetPort: 8000
